# Generated by Django 4.2 on 2023-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calorie',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ккал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Белки'),
        ),
    ]
