# Generated by Django 4.2 on 2023-06-10 15:10

import calorie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=calorie.models.product_directory_path, verbose_name='Изображение продукта'),
        ),
    ]
