# Generated by Django 4.2 on 2023-06-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calorie', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calorie', models.FloatField(default=0, null=True, verbose_name='Общее количество ккал')),
                ('total_fat', models.FloatField(default=0, null=True, verbose_name='Общее количество жиров')),
                ('total_protein', models.FloatField(default=0, null=True, verbose_name='Общее количество белков')),
                ('total_carbohydrate', models.FloatField(default=0, null=True, verbose_name='Общее количество углеводов')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('sum_calorie', models.FloatField(default=0, null=True, verbose_name='Сумма ккал')),
                ('sum_fat', models.FloatField(default=0, null=True, verbose_name='Сумма жиров')),
                ('sum_protein', models.FloatField(default=0, null=True, verbose_name='Сумма белков')),
                ('sum_carbohydrate', models.FloatField(default=0, null=True, verbose_name='Сумма углеводов')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.product', verbose_name='Выбранный продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выбранный продукт',
                'verbose_name_plural': 'Выбранные продукты',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_products',
            field=models.ManyToManyField(blank=True, related_name='carts', to='cart.cartproduct', verbose_name='Выбранные продукты'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Польщовател'),
        ),
    ]
