# Generated by Django 4.2 on 2023-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_calorie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Общее количество ккал'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Общее количество углеводов'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Общее количество жиров'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Общее количество белков'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='sum_calorie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Сумма ккал'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='sum_carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Сумма углеводов'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='sum_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Сумма жиров'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='sum_protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Сумма белков'),
        ),
    ]
